### PR TITLE
 add my logo to SHRK web: https://viewblock.io/zilliqa/address/zil17tsmlqgnzlfxsq4evm6n26txm2xlp5hele0kew

### PR DESCRIPTION
**Pull request by 3FinTony**
# Add New Token Logo

Please follow the below format for adding a token to the Zilswap token list.

## Checklist 

Ensure these have been done:

* [] My token address is keyed by a unique token symbol in tokens.json, matching the ZRC-2 smart contract `symbol` field exactly.
* [] I've added a 64x64 `svg` formatted logo with the filename as <token_symbol>.svg in the /logos folder.
* [] My `svg` logo has no unnecessary metadata and tags.

## Address Verification

My project website is: <FILL ME IN>
This link contains a verification for the added address in `tokens.json`: <FILL ME IN>

### CODE REVIEW

**Comment by 3FinTony** [comment]
i really dont see whaht the issue is in tokens.json   please help

**Comment by RavenXce** [comment]
Please remove the unnecessary .DS_Store files, JPEG flies. Please also include a URL in the PR description which shows your token address within your project website or IPFS domain.

**Comment by 3FinTony** [comment]
My project website is: https://gateway.pinata.cloud/ipfs/QmWjWcpjPUhgE4K3JLC6GgE7RGypdetKaDupmsEgmUc2RY

**Comment by 3FinTony** [comment]
it wont let me delete anything else, is it good now ?

**Comment by 3FinTony** [comment]
should be good to Merge, previous Commits have ben closed

**Pull request closed without merging**
